### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Souparno10** [kmille36/Go-Deploy-Windows-11-NGROK-RDP#1]
'ngrok' is not recognized as an internal or external command,
operable program or batch file.
'ngrok' is not recognized as an internal or external command,
operable program or batch file. 

Error

**Comment by roblox34** [comment]
1. [ ] 1. [ ] 1. [ ] 1. [ ] 1. [ ] 1. Install ### `_it_` First

**Comment by kmille36** [comment]
It work lol, paste script again.
